version: '3.9'

x-common: &common
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
  restart: "unless-stopped"
  stop_grace_period: 5m
  stop_signal: SIGINT
  env_file:
    - .env
  environment:
    - NOTEBOOK_USER:user
    - NVIDIA_VISIBLE_DEVICES:"all"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  working_dir: /root/user
  volumes:
    - WORKSPACE/user:/root/user
    - /etc/localtime:/etc/localtime
  ulimits:
    memlock: -1
    stack: 67108864
  shm_size: "10gb"
  cap_add:
    - NET_ADMIN
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    resources:
      reservations:
        devices:
          - capabilities: [ gpu ]
            count: all

services:
  deepstream:
    <<: *common
    image: ${DOCKER_DOMAIN}rivia/deepstream:${IMAGE_TAG__DEEPSTREAM:-6.4-triton-multiarch}
    hostname: deepstream
    container_name: deepstream
    ports:
      - 0.0.0.0:${DEEPSTREAM_SSH_PORT:-12122}:22
      - 0.0.0.0:${DEEPSTREAM_NOTEBOOK_PORT:-12188}:8888
      - 0.0.0.0:${DEEPSTREAM_RTSP_PORT:-18554}:8554
      - 0.0.0.0:${DEEPSTREAM_EXTRA_PORT_1:-12199}:19999
      - 0.0.0.0:${DEEPSTREAM_EXTRA_PORT_2:-22199}:29999
      - 0.0.0.0:${DEEPSTREAM_EXTRA_PORT_3:-32199}:39999


  rtsp-server:
    <<: *common
    image: ${DOCKER_DOMAIN}aler9/rtsp-simple-server:${IMAGE_TAG__RTSP:-latest}
    hostname: rtsp-server
    container_name: rtsp-server
    ports:
      - 0.0.0.0:${RTSP_RTSP_PORT:-8554}:8554
      - 0.0.0.0:${RTSP_EXTRA_PORT_1:-12299}:19999
      - 0.0.0.0:${RTSP_EXTRA_PORT_2:-22299}:29999
      - 0.0.0.0:${RTSP_EXTRA_PORT_3:-32299}:39999


networks:
  default:
    name: gpu-deepstream
    driver: bridge